"""
Qt Adapter Layer for DFN Cave Studio.

Provides a thin abstraction over PySide6 to allow future migration to PyQt6.
All Qt imports throughout the application should go through this module
rather than importing PySide6 directly.

Usage:
    from dfn_cave_studio.ui.qt_adapter import QtWidgets, QtCore, QtGui
"""

# The adapter intentionally re-exports a broad Qt surface for UI modules.
# ruff: noqa: F401

from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import (
    Qt,
    QObject,
    QThread,
    QThreadPool,
    QRunnable,
    Signal,
    Slot,
    QTimer,
    QMutex,
    QWaitCondition,
    QSize,
    QPoint,
    QRect,
    QModelIndex,
    QAbstractTableModel,
    QAbstractListModel,
    QSettings,
    QCoreApplication,
    QTranslator,
    QLocale,
    QLibraryInfo,
    QEvent,
    QDir,
    QFile,
    QFileInfo,
    QUrl,
    QDateTime,
    QDate,
    QTime,
    QProcess,
    Property,
    QSignalBlocker,
)

from PySide6.QtGui import (
    QAction,
    QKeySequence,
    QIcon,
    QPixmap,
    QColor,
    QFont,
    QPalette,
    QBrush,
    QPen,
    QPainter,
    QCursor,
    QImage,
    QTransform,
    QVector3D,
    QMatrix4x4,
    QScreen,
    QMovie,
    QValidator,
    QIntValidator,
    QDoubleValidator,
    QActionGroup,
    QUndoCommand,
    QUndoStack,
)

from PySide6.QtWidgets import (
    QApplication,
    QMainWindow,
    QWidget,
    QDialog,
    QMessageBox,
    QFileDialog,
    QMenu,
    QMenuBar,
    QToolBar,
    QStatusBar,
    QProgressBar,
    QLabel,
    QPushButton,
    QLineEdit,
    QTextEdit,
    QPlainTextEdit,
    QComboBox,
    QCheckBox,
    QRadioButton,
    QSpinBox,
    QDoubleSpinBox,
    QSlider,
    QTabWidget,
    QStackedWidget,
    QDockWidget,
    QTreeWidget,
    QTreeWidgetItem,
    QListWidget,
    QListWidgetItem,
    QTableWidget,
    QTableWidgetItem,
    QGroupBox,
    QFrame,
    QSplitter,
    QScrollArea,
    QScrollBar,
    QHeaderView,
    QFormLayout,
    QHBoxLayout,
    QVBoxLayout,
    QGridLayout,
    QSizePolicy,
    QSpacerItem,
    QButtonGroup,
    QToolButton,
    QStyleFactory,
    QInputDialog,
    QColorDialog,
    QFontDialog,
    QErrorMessage,
    QWizard,
    QWizardPage,
    QSystemTrayIcon,
    QDialogButtonBox,
)

# Backend bridge (PyVista with Qt)
try:
    from pyvistaqt import QtInteractor as PyVistaQtInteractor
    HAS_PYVISTAQT = True
except ImportError:
    HAS_PYVISTAQT = False

__all__ = [
    "QtCore",
    "QtGui",
    "QtWidgets",
    # Common Core types
    "Qt",
    "QObject",
    "QThread",
    "QThreadPool",
    "QRunnable",
    "Signal",
    "Slot",
    "QTimer",
    "QMutex",
    "QWaitCondition",
    "QSize",
    "QSignalBlocker",
    "QPoint",
    "QRect",
    "QModelIndex",
    "QAbstractTableModel",
    "QAbstractListModel",
    "QSettings",
    "QCoreApplication",
    "QTranslator",
    "QLocale",
    "QLibraryInfo",
    "QEvent",
    "QDir",
    "QFile",
    "QFileInfo",
    # Common GUI types
    "QAction",
    "QKeySequence",
    "QIcon",
    "QPixmap",
    "QColor",
    "QFont",
    "QPalette",
    # Common Widget types
    "QApplication",
    "QMainWindow",
    "QWidget",
    "QDialog",
    "QMessageBox",
    "QFileDialog",
    "QMenu",
    "QMenuBar",
    "QToolBar",
    "QStatusBar",
    "QProgressBar",
    "QLabel",
    "QPushButton",
    "QComboBox",
    "QCheckBox",
    "QSpinBox",
    "QDoubleSpinBox",
    "QSlider",
    "QTabWidget",
    "QStackedWidget",
    "QDockWidget",
    "QTreeWidget",
    "QTreeWidgetItem",
    "QListWidget",
    "QListWidgetItem",
    "QTableWidget",
    "QGroupBox",
    "QSplitter",
    "QScrollArea",
    "QFormLayout",
    "QHBoxLayout",
    "QVBoxLayout",
    "QGridLayout",
    "QSizePolicy",
    "QToolButton",
    "QActionGroup",
    "QInputDialog",
    "QDialogButtonBox",
    "QActionGroup",
    "QUndoCommand",
    "QUndoStack",
    # PyVista Qt bridge
    "PyVistaQtInteractor",
    "HAS_PYVISTAQT",
]
